.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. lmcoin_qt test_lmcoin_qt
clean: FORCE
	$(MAKE) -C .. lmcoin_qt_clean test_lmcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_lmcoin_qt_check
lmcoin-qt lmcoin-qt.exe: FORCE
	 $(MAKE) -C .. lmcoin_qt
